package com.muiezarif.kidsfitness.utils
object Constants{
    val COACH_LOGIN = "COACH_LOGIN"
    val COACH_REGISTER = "COACH_REGISTER"
    val STUDENT_LOGIN = "STUDENT_LOGIN"
    val STUDENT_REGISTER = "STUDENT_REGISTER"
    val STUDENT_TYPE = "STUDENT_TYPE"
    val COACH_TYPE = "COACH_TYPE"
    val STUDENT_CHANGE_CATEGORY = "STUDENT_CHANGE_CATEGORY"
    val STUDENT_CHANGE_LEVEL = "STUDENT_CHANGE_LEVEL"
    val STUDENT_CAT_LESSON_PARTS = "STUDENT_CAT_LESSON_PARTS"
    val STUDENT_CAT_LESSON_PART_VIDEO = "STUDENT_CAT_LESSON_PART_VIDEO"
    const val sp_username="sp_username"
    const val sp_userType="sp_userType"
    const val sp_uid="sp_uid"
    const val sp_email="sp_email"
    const val sp_token="sp_token"
    const val sp_child_category_id="sp_child_category_id"
    const val sp_child_category_slug="sp_child_category_slug"
    const val sp_child_level_slug="sp_child_level_slug"
    const val sp_address="sp_address"
    const val sp_number="sp_number"
    const val sp_lat="sp_lat"
    const val sp_lng="sp_lng"
    const val sp_language="my_lang"
    const val sp_premium_user="is_premium"
    const val sku_monthly_premium="kisszoo_premium_yearly"
}